### ISSUE TITLE
Patches becoming duplicated when trying to reorganize them in a "bank" by dragging. 

### ISSUE THREAD

**Issue by matreve** [meanmedianmoge/zoia_lib#101]
**Describe the bug**
Patches become duplicated when trying to reorganize them in a "bank" by dragging. New slots become populate with the copy of the same patch and the original patch slot can't be changed. 

**To Reproduce**
1. Load a saved bank (json file).
2. Try to move a patch into a different slot by dragging. 
3. The patch can't be moved but instead a copy is created. 
4. Each drag and drop of the patch (or its copy) creates another copy. 
5

**Expected behavior**
Patch to be moved to a new slot without creating a copy. 

**Screenshots**

**Desktop (please complete the following information):**
Windows and Mac OS
Version 1.1
**Additional context**
This happens randomly but is present 90% of the time.

**Comment by matreve** [comment]
https://user-images.githubusercontent.com/57880522/124063119-1b6e4a00-da00-11eb-906f-d351e0614e77.mov

**Comment by meanmedianmoge** [comment]
Thanks for the video. If you reload the Bank tab or scroll, do the duplicates persist? There might be a lag in the slots populating, just want to rule that out.

**Comment by meanmedianmoge** [comment]
Is at least related to #93, if not a duplicate.

**Comment by matreve** [comment]
The #93 doesn’t describe the behavior, does not mention duplication. No way for me to see it’s the same thing.

**Comment by meanmedianmoge** [comment]
Could you comment on the reloading/scrolling question I asked above? I've seen the behavior you mentioned but the dupes go away after either scrolling down on the tables or reloading the tab.

**Comment by matreve** [comment]
Sorry, did not notice this question. Yes, the duplicates persist even if I
go in and out of the "banks" tab. Same when scrolling.

**Comment by meanmedianmoge** [comment]
@matreve Can you try the updated release zip to see if this issue is resolved? I made some changes to the UI which should make it more stable.

**Comment by matreve** [comment]
The behavior when attempting to rearrange the patches in existing banks is
exactly the same as previously, the patches become duplicated.

**Comment by meanmedianmoge** [comment]
I updated the UI to use Fusion - see the latest Mac 1.1 release. If this does not resolve, I don’t know what else will.

**Comment by matreve** [comment]
> I updated the UI to use Fusion - see the latest Mac 1.1 release. If this does not resolve, I don’t know what else will.

What about the Windows version? Why are you closing these issue threads before there is a confirmation of the fix working correctly? It seriously feels like waste of time reporting issues here. When the issue is open there is a greater chance that someone can see it and help you resolve it - it was the case with the other issue recently.
