### ISSUE TITLE
Buttons are barely visible in light mode (Mac) > Dark mode resolves it

### ISSUE THREAD

**Issue by mindtonic** [meanmedianmoge/zoia_lib#106]
**Describe the bug**
The download button does not appear on any of the patches in PatchStorage mode. The tiny greyed out button that barely appears does not do anything.

**To Reproduce**
1. Go to PatchStorage
2. Search for a Patch or Keyword.
3. Scroll down to your desired patch.
4. There is no download button. If there is a barely visible button, it does not do anything.

**Expected behavior**
Be able to download patches from PatchStorage through the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/59553/126185243-0663d26c-7512-43f0-9bd5-b1d1c4811c69.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.14.6
 - ZOIA Librarian Version: 1.1

**Additional context**
THANK YOU!!! I really appreciate your work on this app. It has made the ZOIA a much more useful piece of gear. I am a developer and would be happy to help and support in any way possible.

**Comment by meanmedianmoge** [comment]
Thanks for the bug report! Couple of clarifying questions:

- Do all of the buttons across the tabs show this behavior? For instance, I can make out “Refresh Patch List” on the top right there - is it clickable?

- Could you confirm if this persists when dark mode/alternating row colors are active?

- If you hover over the (barely) visible Download button outlines, does your cursor change to indicate that it is clickable? Is there any status bar (bottom left) text?

- For the rows which seemingly do not have any such Download button - have you previously downloaded those patches, and if so, do they appear in Local Staorage?

10.14 makes this trickier (I run 10.15/11.2 and don’t have any Mojave machines on hand), so I would appreciate any assistance you can provide in testing.

**Comment by mindtonic** [comment]
No problem! Happy to help. This might actually be cause for me to update my OS version. As a developer you can appreciate that OS updates can often cause all kinds of productivity issues!

> Do all of the buttons across the tabs show this behavior? For instance, I can make out “Refresh Patch List” on the top right there - is it clickable?

On LocalStorge, the export and delete buttons are absent:

![image](https://user-images.githubusercontent.com/59553/126198957-71938d63-ccc5-4958-b96a-a23e1d68b4ee.png)

On Folder, the Add To Folder button is absent:

![image](https://user-images.githubusercontent.com/59553/126199043-c8b5e3ec-c029-4d34-9799-891262a8d6bf.png)


> Could you confirm if this persists when dark mode/alternating row colors are active?

**_Dark Mode fixes the issue._** I prefer dark mode anyway so I can stick with this if it's not a priority to fix. I appreciate your time.

![image](https://user-images.githubusercontent.com/59553/126198876-87c05bb1-b002-42ce-b563-979059a2e8c1.png)


> If you hover over the (barely) visible Download button outlines, does your cursor change to indicate that it is clickable? Is there any status bar (bottom left) text?

When hovering over an invisible button:

![image](https://user-images.githubusercontent.com/59553/126199165-ada6c389-ba56-4c5c-a7d3-fe85509d8565.png)

While clicking and dragging over the buttons:

![image](https://user-images.githubusercontent.com/59553/126199203-390140be-1278-454e-b8aa-3fe82e10332b.png)


> For the rows which seemingly do not have any such Download button - have you previously downloaded those patches, and if so, do they appear in Local Storage?

The ones that I have downloaded do appear in Local Storage. I am going to delete `.ZoiaLibrarianApp` and reinstall the app to see if that makes any difference. I will edit this comment when I'm done.


Happy to help in any way you need including screen sharing. Thanks for your time and for this wonderful app.

**Comment by meanmedianmoge** [comment]
Thanks for the update! Dark mode ftw.

Sometimes I forget that light mode exists.. just confirmed this behavior. The buttons are there and will function, but it's very hard to see them. I'll make a change to the css for light mode.

**Comment by mindtonic** [comment]
Awesome! I'm totally a dark mode person, I just got excited about the new update and forgot to switch the view mode. How difficult is it to make the app match the user's default view mode? 

Anyway..... YOU ROCK! 🤘

**Comment by meanmedianmoge** [comment]
It should transfer your saved preference for theme, as long as you didn't wipe the `/.ZoiaLibraryApp` directory in between the update process. The default setup uses light mode, which I will also change.

Btw thank you for your donation and kind words :)

**Comment by meanmedianmoge** [comment]
CSS files were updated for the Mac release.
