### ISSUE TITLE
Zoia Librarian silently fails after replacing ZOIA LIBRARIAN.app (1.1) in /Applications with same version (1.1) on OSX 10.14.6 (including workaround)

### ISSUE THREAD

**Issue by optykali** [meanmedianmoge/zoia_lib#108]
Zoia Librarian silently fails after replacing ZOIA LIBRARIAN.app (1.1) in /Applications with same version (1.1) 

reports "com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000003.ZOIA Librarian[841]): Service exited with abnormal code: 1" in system.log

**To Reproduce**
1. Replace ZOIA LIBRARIAN.app (1.1)
2. Click on ZOIA LIBRARIAN.app
3. Dies.
4. executing via terminal from within ZOIA Librarian.app/Contents/MAC OS/ZOIA LIBRARIAN reports OSError: [Errno 66] Directory not empty: '/Users/User/Library/Application Support/.ZoiaLibraryApp/Banks' -> '/Users/opty/Library/Application Support/.ZoiaLibraryApp/Folders'
[970] Failed to execute script startup
5. deleting folder /Users/User/Library/Application Support/.ZoiaLibraryApp/ resolves the issue.

**Expected behavior**
Launch ZOIA LIBRARIAN

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.6
- Version: 1.1

**Comment by meanmedianmoge** [comment]
You don’t have to delete the whole /.ZoiaLibraryApp backend, just the Banks and/or Folders dir inside there would be enough to resolve this.

This one is interesting though - I’d double check that the transition from 1.0 to 1.1 is successful (delete the whole backend, load up 1.0, then replace with 1.1).

Another question would be how old that previous 1.1 app file is?

**Comment by optykali** [comment]
Interestingly, it seems to work. Let me check if I eventually downgraded to 1.0 and back to 1.1 and this caused the bug. The 1.1 version seem to have been recent binaries from the repo. It might be nothing. I just thought it might be valuable to re-state that deleting (as already stated). Sorry to make a mess here.

**Comment by meanmedianmoge** [comment]
Has this issue come up again @optykali ? If not, will close this out.

**Comment by optykali** [comment]
I tried to replicate it. Issue did not come up again. Eventually it is the lnown uograde issue and I accidentally replaced with an older version. I will keep an eye out
