### ISSUE TITLE
Librarian 1.1 not importing renamed patches or deleting patches from local

### ISSUE THREAD

**Issue by lordradish** [meanmedianmoge/zoia_lib#113]
**Describe the bug**  - reposted from Reddit
If I save a new patch on the Zoia that I made from another and modified, even if I rename it, the librarian won't let me import, because it says the patch already exists (with the name of the old patch I modded and saved with new name).

Also, oddly, it's not letting me delete patches from local storage. It shows it disappearing, but when I restart the program, it's back.

**To Reproduce** problem 1
1. Go to folder view
2. Click on import patch
3. Get error message
4.

**To Reproduce** problem 2
1. Go to personal storage view
2. Click on delete patch. Patch goes away.
3. Restart librarian. Patch is again in personal storage.

As to the patches I was trying to delete, one was one that I'd made from scratch. Another was a mono version I had saved on the pedal of Untold Dozer, from Patch Storage. The second one was the one I'd made, originally a stereo one called OD Vibe. I'd saved and renamed in mono, and renamed the other one to stereo. It wouldn't let me import either, giving me that same msg. It didn't save any multiple versions. When I delete OD Vibe from my local folder, it disappears. When I restart the program, it's back.

**Expected behavior**
For problem 1, I expected it to import.
For problem 2, I expected the preset to permanently delete.

**Screenshots**
enclosed two screenshots to show import error message.
<img width="299" alt="Screenshot1" src="https://user-images.githubusercontent.com/33111644/134014963-65992573-d957-45a3-ac73-174bf24ae3dc.png">

<img width="335" alt="Screenshot2" src="https://user-images.githubusercontent.com/33111644/134015038-35f32b32-ae9a-459e-8be2-99b36bb5fdde.png">

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 19043

**Comment by meanmedianmoge** [comment]
Hi @lordradish apologies for the delay on this - can you try the new release here https://github.com/meanmedianmoge/zoia_lib/releases/tag/1.2

I tried to recreate your bug after making these changes and they didn't seem to pop up. Would appreciate a confirmation so I can close this issue!
