### ISSUE TITLE
Sort by category

### ISSUE THREAD

**Issue by lordradish** [meanmedianmoge/zoia_lib#114]
It would be great to be able to sort lists by category. Sometimes I just want effects, or just want synthesizers, and this would make it MUCH easier.

**Comment by meanmedianmoge** [comment]
The search functionality works with categories and tags as well, in case you didn’t realize/know that.

Otherwise, this is easy enough to add. Thanks for the request!

**Comment by meanmedianmoge** [comment]
This will be added in the upcoming 1.2 release, along with sorting by Tags!
