### ISSUE TITLE
No internet connection error 

### ISSUE THREAD

**Issue by Acidfever** [meanmedianmoge/zoia_lib#116]
When starting the application I get a pop-up box with title" No internet connection" with the text "Failed to retrieve patches from PatchStorage. Please check your internet connection and tryagain."

My internet connection however is fine.

Any suggestions?
Adding Zoia librarian.exe manually to windows firewall doesn't make help.

Windows 10 Pro 64bit build 19043.1237 on Intel core i7-10510u cpu with 16gb ram
Screenshot of the error:
![zlerror](https://user-images.githubusercontent.com/74898315/136985001-a80eaa0e-75e9-4be4-9ccd-212f349a2d18.png)
.

**Comment by meanmedianmoge** [comment]
We believe to have a fix for this issue; a new release should be just around the corner.

**Comment by tgrabia** [comment]
Sorry to pester but has this moved any closer to release?

**Comment by meanmedianmoge** [comment]
Hey @tgrabia - I ran into a pretty major bug as I was going through the deployment steps, so that diverted my attention elsewhere, and then life got in the way, so I apologize for the lengthy delay. Hoping to finalize before the end of the year.

**Comment by tgrabia** [comment]
@meanmedianmoge Not sure what happened but it is working now on Windows for me.  May have been a Windows update but it launched and connected fine.

**Comment by Acidfever** [comment]
Still no luck here sadly, exact same error with fully updated windows10. But to be honest I lost interest for now. The developer did a public request for beta testers but ignores a complete showstopper bug in the current windows release for months. Just build a version with the bug solved so people on windows can at least continue testing.

**Comment by meanmedianmoge** [comment]
Glad to hear it @tgrabia.

@Acidfever master branch has the fix if you want to compile from source. I didn’t ignore the bug - as per my prior comment, we made a fix and pushed it, then during deployment we found a much larger bug that is still unresolved.
