### ISSUE TITLE
I would like to collaborate to file «documentation/binary format.pdf»...

### ISSUE THREAD

**Issue by marcuslupinus** [meanmedianmoge/zoia_lib#117]
Hi, I'm new to github so excuse me if its the wrong place for this.
I'd like to develop a C# .Net tool for investigating the inside of zoia patches - show how a patch is built.  My project relies extensively on the info from your «documentation/binary format.pdf» file, I think it would be better if we maintained only one such file.
So I would like to contribute in updating it.
What do you think about that ?
If you are interested we would need to discuss (maybe outside github...) about how to do this task because I don't have a PDF editor and would prefer using something like MS Word (.docx) because of it's ability to manage comments and revisions directly.

Note: I am a retired software developer (university degree in computer science from mid 1980's) and I have extensive technical documentation experience but even though I can work in English, I am French (Canadian) so I make mistakes here and there.

Looking forward to doing this.

**Comment by djigneo** [comment]
Heya, I wrote the original doc. You might want to take a peek at my repo: https://github.com/djigneo/zoia_lib/tree/master/ZoiaFormatInterpreter which has a C# implementation started.

I should be able to check in a word document version somewhere.

**Comment by meanmedianmoge** [comment]
Thanks @djigneo. I have a word version of the pdf as well, can commit here as a starting point.

The interest and offer are very much appreciated @marcuslupinus, would love to see what you end up contributing!

Will close this once I upload the docx.

**Comment by djigneo** [comment]
Added to my repo as well.

**Comment by marcuslupinus** [comment]
ok thanks for the prompt reply(ies).
