### ISSUE TITLE
Librarian 1.1: patches downloaded from PatchStorage do not appear in local patches pane in Folders view

### ISSUE THREAD

**Issue by markcrosbie** [meanmedianmoge/zoia_lib#118]
**Describe the bug**
When I download a new patch from the PatchStorage tab in shows up in the LocalStorage tab correctly. But if you go to the Folders tab then the newly downloaded patch does not appear in the rightmost list of local patches. Quitting the app and restarting makes it appear.

**To Reproduce**
1. Go to PatchStorage tab
2. Choose a patch to download
3. Verify patch is downloaded in Local Storage tab
4. Open Folders tab
5. Patch does not appear in local patches list on the right
6. Quit app and restart
7. Go to Folders tab
8. Downloaded patch now appears in the list of local patches on the right

**Expected behavior**
Newly downloaded patch from patch storage should appear in local patches list in Folders tab

**Desktop (please complete the following information):**
 - OS: Mac OS 11.6.2
 - Version 1.1

**Comment by meanmedianmoge** [comment]
Hey @markcrosbie, thanks for the report. Does the patch show up if you hit enter in the search bar? That should trigger the table refresh without a restart.

**Comment by meanmedianmoge** [comment]
Also is this a dupe of #107 ?

**Comment by markcrosbie** [comment]
Whoops, yes it is. I'll close this one. And if I do the search bar on Folders it does seem to refresh. That confused me at first. Thanks.
