### ISSUE TITLE
No "internet connection" at startup

### ISSUE THREAD

**Issue by introspeckle** [meanmedianmoge/zoia_lib#119]
hi, thanks for designing this app. I am running Mac 12.1 Monterey. I was running the Zoia Librarian app for the first time last night with no issues. this morning I tried to use it again, and ever since I have gotten the error message "failed to retrieve patches from Patchstorage. Please check your internet connection." my Internet connection is fine, so I'm not sure if I'm doing something wrong or not. I tried updating my Mac OS after it stopped working but that didn't help either. thanks for your help.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by introspeckle** [comment]
[]
<img width="1440" alt="Screen Shot 2022-01-25 at 1 05 21 PM" src="https://user-images.githubusercontent.com/98427865/151060153-a95d82ae-bbd4-4482-b94a-83ad72b52743.png">
(url)

**Comment by meanmedianmoge** [comment]
#116 dupe, though for Mac.

@introspeckle I don’t have the means to test on Monterey currently, but I’ll try my best. This is not an issue on Big Sur or below.

**Comment by introspeckle** [comment]
Thank you. I also deleted the app and reinstalled but that didn't help.

**Comment by introspeckle** [comment]
Hi, I'm just checking in to see if there is any update on this issue? I'm still having the issue, and it has not resolved itself. Thanks.

**Comment by meanmedianmoge** [comment]
Hi @introspeckle can you try the release here: https://github.com/meanmedianmoge/zoia_lib/releases/tag/1.2

Again, I don't have direct access to a Monterey machine so I may need some time to figure this out if the issue persists. Thanks for your patience.

**Comment by introspeckle** [comment]
I deleted the old app and installed the new one. However, when I open the new app, the Zoia Librarian icon just "bounces" as if it's going to load, then quits. The same results occur after repeated attempts. Do you know why that is occurring? Thanks

**Comment by meanmedianmoge** [comment]
@introspeckle can you run the following in a terminal window and reply with any error message that pop-up? This assumes the unzipped app file is in your Downloads folder.

```
cd Downloads
./ZOIA\ Librarian.app/Contents/MacOS/ZOIA\ Librarian
```

**Comment by introspeckle** [comment]
Does this help?
<img width="1440" alt="Screen Shot 2022-03-10 at 7 54 01 PM" src="https://user-images.githubusercontent.com/98427865/157799735-77193840-fd8f-44af-b997-94d9380ccd99.png">

**Comment by meanmedianmoge** [comment]
Close! Unzip the file (double click and you’ll see a “ZOIA Librarian” file there, with no extension) and try again.

**Comment by introspeckle** [comment]
Gotcha. Is this wha you need?
<img width="1440" alt="Screen Shot 2022-03-11 at 3 14 41 PM" src="https://user-images.githubusercontent.com/98427865/157987134-d8442c48-a844-4bfa-afed-767921e245ba.png">

**Comment by meanmedianmoge** [comment]
Yep that’s the ticket, thank you! I can debug from here, will let you know when I have a new version for you to test.

**Comment by introspeckle** [comment]
Thank you. I appreciate your help. So far so good.
