### ISSUE TITLE
Crash on relaunch of app

### ISSUE THREAD

**Issue by TurboTodd2000** [meanmedianmoge/zoia_lib#125]
I've been successfully using the app for a couple of days, just exploring Patch Storage. Today after exporting folders to a SD card I've been unable to relaunch the app.

This is on macOS 10.14.6 (aka Mojave)

After several unsuccessful attempts I deleted the .ZoiaLibraryApp and the app, unzipped and moved a new copy of the app to Applications and tried again. Got the same result so looking on line I found an issue report from 2020 and tried launching from Terminal.

If I launch it from the terminal I get this...

sudo /Applications/ZOIA\ Librarian.app/Contents/MacOS/ZOIA\ Librarian 

Traceback (most recent call last):
  File "startup.py", line 38, in <module>
  File "ZOIALibrarian_main.py", line 397, in __init__
  File "ZOIALibrarian_main.py", line 1092, in sort_and_set
  File "utilities.py", line 71, in sort_metadata
  File "utilities.py", line 71, in <lambda>
TypeError: string indices must be integers
[825] Failed to execute script startup

These messages also appear in the OS X Console....

default	20:07:33.496017 -0700	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/ZOIA%20Librarian.app/Contents/, NSFilePath=/Applications/ZOIA Librarian.app/Contents/PlugIns, NSUnderlyingError=0x7fdf89c69c80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	20:07:33.524750 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
default	20:07:33.524870 -0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ZOIA Librarian
default	20:07:34.103866 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so signature not valid: -67050
default	20:07:34.101395 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/numpy/core/_multiarray_umath.cpython-39-darwin.so' is adhoc signed.
default	20:07:34.155436 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/libopenblas64_.0.dylib' is adhoc signed.
default	20:07:34.166496 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/libopenblas64_.0.dylib signature not valid: -67050
default	20:07:34.184228 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/libgfortran.3.dylib' is adhoc signed.
default	20:07:34.186149 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/libgfortran.3.dylib signature not valid: -67050
default	20:07:34.187458 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/libquadmath.0.dylib' is adhoc signed.
default	20:07:34.188892 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/libquadmath.0.dylib signature not valid: -67050
default	20:07:34.198707 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/libgcc_s.1.dylib' is adhoc signed.
default	20:07:34.200642 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/libgcc_s.1.dylib signature not valid: -67050
default	20:07:34.499259 -0700	kernel	AMFI: '/Applications/ZOIA Librarian.app/Contents/MacOS/numpy/linalg/_umath_linalg.cpython-39-darwin.so' is adhoc signed.
default	20:07:34.501715 -0700	amfid	/Applications/ZOIA Librarian.app/Contents/MacOS/numpy/linalg/_umath_linalg.cpython-39-darwin.so signature not valid: -67050
default	20:07:42.899959 -0700	ZOIA Librarian	Current system appearance, (HLTB: 1), (SLS: 0)
default	20:07:42.900553 -0700	ZOIA Librarian	Post-registration system appearance: (HLTB: 1)
default	20:07:42.963535 -0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ZOIA Librarian
default	20:07:43.086673 -0700	ZOIA Librarian	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600000a8a940
 (
    "<NSAquaAppearance: 0x600003cd8240>",
    "<NSSystemAppearance: 0x600003cd8380>"
)>
default	20:07:43.134240 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
error	20:07:43.146127 -0700	tccd	Failed to copy signing info for 772, responsible for file:///Applications/ZOIA%20Librarian.app/Contents/MacOS/ZOIA%20Librarian: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
default	20:07:43.148741 -0700	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.myidentifier, type: 0: 0x7febc7624350 at /Applications/ZOIA Librarian.app
default	20:07:48.135646 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : ZOIA Librarian
default	20:07:48.135658 -0700	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: ZOIA Librarian
default	20:07:48.135679 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: ZOIA Librarian
default	20:07:48.142260 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 0;
        BundleID = "com.myidentifier";
        Hide = 0;
        Path = "/Applications/ZOIA Librarian.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.terminal";
        Hide = 0;
        Path = "/Applications/Utilities/Terminal.app";
    },
        {
        BackgroundState = 2;
        BundleID = "org.mozilla.firefox";
        Hide = 1;
        Path = "/Applications/Firefox.app";
    },
        {
        BackgroundState = 2;
        BundleID = "qnap.com.qfinder";
        Hide = 1;
        Path = "/Applications/Qfinder Pro.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.devon-technologies.agent";
        Hide = 0;
        Path = "/Applications/DEVONagent.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.wacom.wacom-desktop-center";
        Hide = 1;
        Path = "/Applications/Wacom Tablet.localized/Wacom Desktop Center.app";
    }
)
default	20:07:48.601389 -0700	ZOIA Librarian	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x7fff4f043ef7 isSys=NO) err=0/noErr
default	20:07:48.721795 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:ZOIA Librarian, _appTrackingState = 2
default	20:07:48.721810 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: ZOIA Librarian, quit, updating active tracking timer
default	20:07:53.722778 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 0;
        BundleID = "com.myidentifier";
        Hide = 0;
        Path = "/Applications/ZOIA Librarian.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.terminal";
        Hide = 0;
        Path = "/Applications/Utilities/Terminal.app";
    },
        {
        BackgroundState = 2;
        BundleID = "org.mozilla.firefox";
        Hide = 1;
        Path = "/Applications/Firefox.app";
    },
        {
        BackgroundState = 2;
        BundleID = "qnap.com.qfinder";
        Hide = 1;
        Path = "/Applications/Qfinder Pro.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.devon-technologies.agent";
        Hide = 0;
        Path = "/Applications/DEVONagent.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.wacom.wacom-desktop-center";
        Hide = 1;
        Path = "/Applications/Wacom Tablet.localized/Wacom Desktop Center.app";
    }
)
default	20:11:28.208481 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
default	20:11:28.208516 -0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ZOIA Librarian
default	20:11:35.050946 -0700	ZOIA Librarian	Current system appearance, (HLTB: 1), (SLS: 0)
default	20:11:35.051593 -0700	ZOIA Librarian	Post-registration system appearance: (HLTB: 1)
default	20:11:35.087293 -0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ZOIA Librarian
default	20:11:35.156655 -0700	ZOIA Librarian	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x60000180af80
 (
    "<NSAquaAppearance: 0x600002e34500>",
    "<NSSystemAppearance: 0x600002e34000>"
)>
default	20:11:35.383106 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
default	20:11:35.391515 -0700	hidd	Connection added: IOHIDEventSystemConnection uuid:CF8D2A5B-0113-49E0-81BF-440BF7AD4A91 pid:795 process:ZOIA Librarian type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1
error	20:11:35.394609 -0700	tccd	Failed to copy signing info for 795, responsible for file:///Applications/ZOIA%20Librarian.app/Contents/MacOS/ZOIA%20Librarian: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
default	20:11:35.398545 -0700	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.myidentifier, type: 0: 0x7febc740dca0 at /Applications/ZOIA Librarian.app
default	20:11:40.189659 -0700	ZOIA Librarian	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x7fff4f043ef7 isSys=NO) err=0/noErr
default	20:11:40.253521 -0700	hidd	Connection removed: IOHIDEventSystemConnection uuid:CF8D2A5B-0113-49E0-81BF-440BF7AD4A91 pid:795 process:ZOIA Librarian type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:0
default	20:11:40.279701 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:ZOIA Librarian, _appTrackingState = 2
default	20:11:40.279717 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: ZOIA Librarian, quit, updating active tracking timer
error	20:11:47.439129 -0700	tccd	failed to get text offset for /Applications/ZOIA Librarian.app/Contents/MacOS/ZOIA Librarian: (#3) No such process
default	20:15:59.708257 -0700	sudo	toddkidder : TTY=ttys000 ; PWD=/Users/toddkidder ; USER=root ; COMMAND=/Applications/ZOIA Librarian.app/Contents/MacOS/ZOIA Librarian
default	20:16:07.364284 -0700	ZOIA Librarian	Current system appearance, (HLTB: 1), (SLS: 0)
default	20:16:07.365148 -0700	ZOIA Librarian	Post-registration system appearance: (HLTB: 1)
default	20:16:07.399096 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
default	20:16:07.399246 -0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : ZOIA Librarian
default	20:16:07.402227 -0700	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/ZOIA%20Librarian.app/Contents/, NSFilePath=/Applications/ZOIA Librarian.app/Contents/PlugIns, NSUnderlyingError=0x7fb684e32970 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	20:16:07.474999 -0700	ZOIA Librarian	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x7ff6d4005cb0
 (
    "<NSAquaAppearance: 0x7ff6d4004e20>",
    "<NSSystemAppearance: 0x7ff6d40054c0>"
)>
default	20:16:07.505274 -0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: ZOIA Librarian, ready, updating active tracking timer
default	20:16:07.692652 -0700	hidd	Connection added: IOHIDEventSystemConnection uuid:EE536E34-C909-4603-89A6-FFA2AAD80A1D pid:825 process:ZOIA Librarian type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1
default	20:16:12.507927 -0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : ZOIA Librarian
default	20:16:12.507938 -0700	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: ZOIA Librarian
default	20:16:12.640362 -0700	ZOIA Librarian	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x7fff4f043ef7 isSys=NO) err=0/noErr
default	20:16:12.696810 -0700	hidd	Connection removed: IOHIDEventSystemConnection uuid:EE536E34-C909-4603-89A6-FFA2AAD80A1D pid:825 process:ZOIA Librarian type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:0
default	20:16:12.719839 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:ZOIA Librarian, _appTrackingState = 2
default	20:16:12.719856 -0700	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: ZOIA Librarian, quit, updating active tracking timer

Hope this is of use in tracking the issue down.

**Comment by meanmedianmoge** [comment]
Ready to go for 1.3
