### ISSUE TITLE
Failed to retrieve the patch metadata from PatchStorage

### ISSUE THREAD

**Issue by personalnadir** [meanmedianmoge/zoia_lib#126]
**Describe the bug**
Clicking on the PatchStorage tab in the librarian produces a pop dialogue with the message: "Failed to retrieve the patch metadata from PatchStorage." Selecting "Show Details" displays the message "unsupported operand type(s) for +: 'dict' and 'list'"

**To Reproduce**
1. Click on PatchStorage tab

**Expected behavior**
The patches available on PatchStorage are displayed 

**Screenshots**
![Screenshot 2022-09-18 at 13 15 32](https://user-images.githubusercontent.com/559503/190901627-520b8d1f-e56f-42c3-aea3-7aeac6781b5a.png)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 12.5.1

**Comment by personalnadir** [comment]
I have tested this with a fresh download of version 1.2 and confirmed it produces the same result

**Comment by loresdef** [comment]
Hi, 

I am encountering the same issue,

OS: macOS Catalina
Version 10.15.7

I've tried re-installing both version 1.1 and 1.2 with fresh downloads as well. But both give similar errors;
V 1.2 
<img width="422" alt="Schermafbeelding 2022-09-18 om 15 06 07" src="https://user-images.githubusercontent.com/113841050/190905022-49db90f6-85e5-45e2-bae4-19edaded6bba.png">

V 1.1
<img width="422" alt="Schermafbeelding 2022-09-18 om 15 41 03" src="https://user-images.githubusercontent.com/113841050/190905622-07325316-ca84-4222-96ab-3ea4157daf74.png">

**Comment by meanmedianmoge** [comment]
Hi, thanks for the report @personalnadir @loresdef. This is due to an issue with the underlying PS API. I will reach out to the maintainer of that project and see if we can find a resolution. Apologies for the inconvenience.

```
{'code': 'rest_cannot_access',
 'message': 'DRA: Only authenticated users can access the REST API.',
 'data': {'status': 401}}
 ```

**Comment by meanmedianmoge** [comment]
I just got word from folks at Patchstorage - it should be resolved now. Please confirm when you get a chance @personalnadir @loresdef and I will close.

For reference, they are working on updating the API so I will try to keep the transition going as smooth as possible.

**Comment by personalnadir** [comment]
@meanmedianmoge working for me now
