### ISSUE TITLE
Importing modified patches

### ISSUE THREAD

**Issue by function-store** [meanmedianmoge/zoia_lib#134]
I have a bunch of patches that I downloaded and modified to my liking. If I want to back them up in my Local Storage it is now not possible as any form of Import action will result in a warning.

I'd like the possibility to import them with my own tag, as a new version to my local storage at least.

Or is there a better way than just manually backing up the folders? Also what if I want to re-use the modified patch in another folder? I currently have to manually copy and paste it over?

Thanks for the software by the way, even with its flaws it gives so much usability to the Zoia!

**Comment by meanmedianmoge** [comment]
I've modified the behavior of imports and this should now work as intended!
