### ISSUE TITLE
New sorting option: sort by latest downloaded

### ISSUE THREAD

**Issue by function-store** [meanmedianmoge/zoia_lib#136]
When browsing for new patches I find it really hard to locate the ones I just downloaded to my Local Storage. Something along the lines of sort by latest downloaded would really help the experience!

**Comment by meanmedianmoge** [comment]
The current sort option default is by updated date, so newer published/updated patches will be at the top. You can also utilize the search feature to narrow down the list.

To be clear, I think this is a good idea, but it might be a little confusing to have two different date sorting methods.
