### ISSUE TITLE
Expanded view not working

### ISSUE THREAD

**Issue by Pick-Ur-Patch** [meanmedianmoge/zoia_lib#139]
**Describe the bug**
Upon attemptin to expand the patch view I get an error

**To Reproduce**
1. Go tothe graphical layout of any patch
2. Click on Expand
3. See error

**Expected behavior**
to see expanded view of patch layout

**Screenshots**
![image](https://github.com/meanmedianmoge/zoia_lib/assets/143564121/27e131a4-d4dc-4e01-9e25-f93068166c80)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]  Win 10

**Additional context**

**Comment by meanmedianmoge** [comment]
This has already been addressed in the code, I just need to deploy the release for Windows. Thanks!

**Comment by Pick-Ur-Patch** [comment]
I downloaded the zip again and re-extracted a couple of times.  On the third try all seemed to work as it should.

**Comment by Pick-Ur-Patch** [comment]
How do I zoom in the expanded view?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by meanmedianmoge** [comment]
Should just be a mouse scroll action, either on a selected region (double click and drag to highlight) or the whole patch.
