### ISSUE TITLE
Some patches give a "Errno 20, not a directory" error.

### ISSUE THREAD

**Issue by Acidfever** [meanmedianmoge/zoia_lib#141]
**Describe the bug**
Some patches give a "Errno 20, not a directory" error.

**To Reproduce**
1. Go to 'The patchstorage tab'
2. Click on 'Recombinator V2 -- a destructive/reconstructive glitch delay-looper]
3. You will get the error:
_"Failed to download the patch from PatchStorage.

[Errno 20] Not a directory: '/Users/<username>/Library/Application Support/.ZoiaLibraryApp/173362/034_zoia_Recombinator_V2.bin'"_

4. The file is downloaded and can be found in the backend folder but isn't show in the local storage folder.

5.. When you click the download again you get: "Unfortunately, that patch is not in a supported format."

6. Also, you cannot re-download the patch since the button is greyed out when you leave and come back to the patchstorage tab.

**Expected behavior**
The patch is downloaded and is shown in the local storage tab

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 
 - Version 14.3 (but also didn't function with 14.2)

**Comment by meanmedianmoge** [comment]
Thanks for reporting! I’ve identified the issue and will update the release bundles with the fix shortly.

**Comment by meanmedianmoge** [comment]
Fixed, please re-download 1.3 from the release page; I've replaced the files for Mac (Windows version coming shortly).
