### ISSUE TITLE
Samples downloading fails on Windows

### ISSUE THREAD

**Issue by joebowbeer** [meanmedianmoge/zoia_lib#145]
**Describe the bug**
None of the Samples downloaded are valid .wav files.
Instead, the files contain the file path (string) of the patch.

Patches affected:

166213, 166218, 167200, 167202, 167486, 173483, 173781 (DlW Drums)

The contents of `Samples/173781/DlW Crash 3.wav` are:

`C:\Users\xxxxx\AppData\Roaming\.ZoiaLibraryApp\173781\DlW Crash 3.wav` (69 bytes)

**To Reproduce**
1. Download DlW Drums
2. Look in Samples folder
3. See that the .wav files are only 60 or 70 bytes long

**Expected behavior**
Playable drum samples.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Version 22H2

**Comment by meanmedianmoge** [comment]
Resolved, set to be in the upcoming bug-fix release. Thanks!
