### ISSUE TITLE
App crashes straight after square logo ZOIA appears on the screen. (OS X 15.1)

### ISSUE THREAD

**Issue by lionelf108** [meanmedianmoge/zoia_lib#148]
Hello.

I use MacBook Pro M3 with MAC OS 15.1. When I run Zoia Librarian 1.3. App it crashes immediately after square logo appears on the screen. I tried to install both versions ARM and Intel and it didn't help. 

After unsuccessful installation I tried to instal v1.2 and v1.1 - they both work, but I need to run app several times to open it. Sometimes it just jumps in a tray and closes after 20-30 seconds, but after few tries it works. 

I use MacBook Pro 14 M3 Pro, it's new, I bought it last week. Before I used MacBook Pro with intel chip and never had any problems with any versions (1.1; 1.2; 1.3).

From discord I know that people with MAC OS 15.1 don't have this problem. 

I would be very grateful to anyone who could fix this bug.

Thanks

**Comment by meanmedianmoge** [comment]
Same issue as #147 

I've identified the issue - will get a fix out asap. Thanks!

**Comment by meanmedianmoge** [comment]
Resolved, set to be in the next bug-fix release. Thanks!
