### ISSUE TITLE
"Local Storage" columns scale/ adjust under adjacent columns

### ISSUE THREAD

**Issue by Ch3ryl** [meanmedianmoge/zoia_lib#36]
**OS**: Windows 10, 64 

**Description:**
When a user navigates to the local storage view and slides the divider to the right or left from the default position, the column widths do not scale. The user has to manually adjust in between column headers. The bug: Adjusting these headers, the columns do not scale or shift with the adjustment until the user releases the cursor. See video for example.

**Reproduction Steps**

1. Start the executable
2. If you do not have some patches in your local storage download one or a couple
3. Navigate to the "Local Storage" tab
4. Adjust the divider between the patches in storage and their details either to the left or right
5. Observe the columns widths for the patches do not change
6. Hover over to the patch files and the divisions between column headers until you see double arrows. Adjust and column width to each end of the screen. See odd layering until you let go of the mouse.

![image](https://user-images.githubusercontent.com/50628195/87716406-d31d3400-c77c-11ea-9d31-29542ca000a1.png)

[2020-07-16 15-58-24.zip](https://github.com/meanmedianmoge/zoia_lib/files/4933941/2020-07-16.15-58-24.zip)
(Video ^^)

_Some UI feedback_ - having the ability to adjust the column width anywhere along the division would be easier to navigate. Also perhaps having the default column width be based on a wider Patch name size?

**Comment by john-breton** [comment]
Although the main issue here has been corrected and should not be an issue in the Beta 2 release, I'm leaving this Issue open since I do want to add the ability to adjust the column width anywhere along the division. For some reason, this change has been more complicated than I anticipated, but I am working hard to try to get it implemented!
