### ISSUE TITLE
SD Card View not populated

### ISSUE THREAD

**Issue by dantahoua** [meanmedianmoge/zoia_lib#37]
Whatever "SD card location" I choose (folder on the SD or root of the SD), nothing is populated in the Patch column.
The Import All Patches button is greyed.

Importing multiple patches menu option is working.

Not that I have multiple folder on my SD Card and nothing in the root folder. I also tried to copy all the patch to root folder, no more chances...

**Comment by john-breton** [comment]
There was an error in the initial beta-1 release that caused the SD Card View tab to not behave properly. I updated the release last night to correct the issue. Could you let me know when you downloaded the release? If you got it today, could you include an image of the issue if possible?

**Comment by dantahoua** [comment]
Ooh!  :o I'll download the new release, should probably be just that! :) I'll let you know.

**Comment by dantahoua** [comment]
It's alright, you can close this issue... :)
