### ISSUE TITLE
Patches not imported from SD card Mac OS Catalina

### ISSUE THREAD

**Issue by markcrosbie** [meanmedianmoge/zoia_lib#38]
I've got 15 patches in a folder on the SD card. When I select the folder in 'SD Card View' and click 'Import all patches' only 5 of the patches are imported.I can import the remaining patches one-by-one by clicking 'Click me to import!'

**Comment by john-breton** [comment]
Thanks for the report. I am not sure whether or not this is a Mac specific, so I need a bit more information.
Would you be able to list the names of the 15 patches that you were attempting to import? Additionally, could you provide the names of the 5 that did import using the "Import all patches" button?

**Comment by meanmedianmoge** [comment]
Mark, could you sent a screenshot of the output of the SD card view and bank you're trying to import all from? I just tested this and was able to import all patches from an SD. Something to note: the librarian will detect if patch binaries are identical and neglect to import patches you already have. But since you're able to import one-by-one, that doesn't seem to be the case here.

**Comment by markcrosbie** [comment]
Sure - I've attached 3 files; the view of the patches stored on the SD card, the SDcard view window in the librarian where I click 'Import All Patches' and the resulting 5 patches that are imported (and randomly renamed) into the Local Storage view.

![filelist](https://user-images.githubusercontent.com/6270801/88454021-2883d000-ce64-11ea-882b-d8fc9c51321a.png)

![importall](https://user-images.githubusercontent.com/6270801/88454010-15710000-ce64-11ea-8102-1b071e192b1b.png)
![result](https://user-images.githubusercontent.com/6270801/88454012-186bf080-ce64-11ea-8f16-2094b76cfc4a.png)

**Comment by markcrosbie** [comment]
Looking back now I realise the patches were not named with _zoia_ in the name prefix which might have confused the importer code. Feel free to close this as not a bug.

**Comment by john-breton** [comment]
In beta-2, lacking the \_zoia\_ prefix shouldn't confuse the application and importing should behave normally.
