### ISSUE TITLE
Local storage view on Mac OS - Title column does not retain dragged size

### ISSUE THREAD

**Issue by markcrosbie** [meanmedianmoge/zoia_lib#40]
It's possible to resize the Title column in the Local Storage View by right-dragging the edge of the column. This allows me to resize it to read the patch names (default sizing displays only 1 letter of the patchname)

This new column size is not retained if I click away from Local Storage View (say into SD Card View)

I have to resize the column each time.

OS: Mac OS 10.15.5

**Comment by john-breton** [comment]
Due to the changes involved with saving the application settings on exit, this bug is no longer occurring. Thank you again for catching it!
