### ISSUE TITLE
Import from SD card not working with folders using certain typographic marks (Windows beta 1)

### ISSUE THREAD

**Issue by chmjacques** [meanmedianmoge/zoia_lib#46]
I have a number of folders that use the format "XX.YY" (month and day in most cases; a form of versioning for my folders).

The Librarian does not seem to be able to import patches from these folders.  The patches will populate the lower portion of the screen, but they cannot be imported.  (Oddly, patches from these folders _can_ be deleted.)

I tried other folders without periods in their names, including underscore ( _ ); all of these worked as expected.  But in the case of folders that possessed periods, neither the "Import all patches" or patch-specific import options worked.

None of my other folders contain other typographical marks, aside from the two mentioned, so I could not test further than those two cases.

(Mike had me check the RoamingData; they weren't being saved to the local directory and not recognized.  They just weren't being saved at all.)

**Comment by john-breton** [comment]
Thanks for catching this. I just tested and confirmed that folders with a "." in their name were causing the importing code to fail. I've since corrected the issue and a fix will be pushed to the Beta 2 branch today.
