### ISSUE TITLE
Font changes/resize are inconsistent throughout the application.

### ISSUE THREAD

**Issue by john-breton** [meanmedianmoge/zoia_lib#57]
**Description**
- This bug pertains to the fact that when a user modifies the font size, modifies the font family, or switches the theme, inconsistencies with the font occur. This ranges from the size of table headers shrinking in size, to the incorrect font being applied after a theme switch. 

**To Reproduce**
- Incorrect font size
 1. Increase/decrease the font size.
 2. Notice the font size for headers, tabs, and radio buttons fail to scale alongside the rest of the font. 
- Incorrect font
 1. Set the font to any of the font families.
 2. Switch the theme of the application.
 3. Notice that the font family is not reflective of what has been previously specified.

**Expected behavior**
The font should be consistent throughout the application and should not be affected by theme changes or font resizing.

**Desktop**
 - OS: Windows 10
 - Version: Beta 2/Beta 3

**Comment by meanmedianmoge** [comment]
This has been mostly completed - I could not figure out how to apply the font changes to the horizontal or vertical headers in the tables (tried to use setStyleSheet QHeaderView instead but still wouldn't take..). Closing for now, as the main issue has been addressed.
