### ISSUE TITLE
Patch bank usability feature ideas

### ISSUE THREAD

**Issue by djigneo** [meanmedianmoge/zoia_lib#61]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Banks tab:
- To add a patch to the bank, a user could double-click a patch from the patch list.
- Allow multi-select for patch list
- When dragging one or more files from patch list, the patches are dropped in the last-most empty slot (or the first empty spot)
- When dragging within a bank list to re-order the patches (allowing inserting between two patches), allow multi-selection. (It looks like multi-select is allowed, but doesn't reorder multiple.)
- By default, hide patches from patch list which have already been added to bank.

**Describe alternatives you've considered**
n/a, these are just suggestions based on how I first attempted to use the program.

**Additional context**

**Comment by meanmedianmoge** [comment]
Already done:
- Multiple selections within banks (works two ways.. shift to select list or ctrl/cmd to select items)
- Reorder multiple (via replacement)

Working on:
- Double click to add patches to bank (will map it to the first open slot)
- Multiple selections from local table to bank (tricky, but doable)

Maybe:
- Hide patches that have already been added (I don't see the harm of allowing multiples? But this seems like a common sense thing.. will investigate)

Won't do:
- Inserting between patches in a bank (currently it does a replacement if there is overlap)
