### ISSUE TITLE
Column resizing (add reset-to-default option)

### ISSUE THREAD

**Issue by chmjacques** [meanmedianmoge/zoia_lib#62]
**Describe the bug**
Rather than resizing columns relative to one another, when the column borders are moved to expand, the columns adjacent to this column can disappear behind the column they are next to.  I'm having some trouble trying to figure out how to make each column the size I would like.

**To Reproduce**
Move a column's borders to expand it.

**Expected behavior**
Adjacent columns to the column with expanded borders should maintain their size and simply be shifted/pushed in the direction of the expansion.

If not this, then maybe a finite limit to how small a column can be made?  Or some indication of a hidden column?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version beta-3

**Additional context**

**Comment by meanmedianmoge** [comment]
@chmjacques could you provide a screenshot? I believe I know what you're referring to, but it might help to have context. Also, are the panel/table sizes not saving upon closing the app? You shouldn't have to resize every time.

**Comment by chmjacques** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/68959237/91923601-c1490f00-ec9e-11ea-9662-47cfae5112d6.png)

I would have but I only just now figured out how to attach files.  So, basically, this screenshot shows the title column pushing everything else behind the download column.

Since there's no left/right scroll (at least that I could figure out, see below), it just felt... weird, and it was really easy to mess up my screen, and then harder to un-mess it.

Hi, I'm Christopher, you may remember me as the technologically-inept one.

**Comment by chmjacques** [comment]
And yes, the resizes are saving, but in my case, that was a detriment, because I hoped to get a reset to default after I messed things up pretty bad.

Maybe that's also a simpler option, at least in the meantime:  some resize to default option.

**Comment by meanmedianmoge** [comment]
Reset to default would be a nice addition - for now, you can go into the backend path and look for a preference file (APPDATA/Roaming/.ZoiaLibrarian/pref.json). If you close out of the app and delete that file, it should load to the default sizing.

I’ll work on making that an option in the toolbar (to automatically clear those preferences as a way to resize to default).

I’m honestly not sure about the left/right scroll bar... it might be due to the columns being so tiny.

**Comment by meanmedianmoge** [comment]
Feature has been added under the "File" toolbar tab - it will reset the UI window sizes. Closing the application will continue to save the current settings in the preferences file.
