### ISSUE TITLE
Problem exporting banks to sd

### ISSUE THREAD

**Issue by Poenauta** [meanmedianmoge/zoia_lib#70]
**Describe the bug**
When exporting banks to SD card, a folder will be created in the card with the name of the bank but without any patches in it.

**To Reproduce**

1. Create a new bank and save it. 
2. Click on export bank. A pop up asks to enter a name for the bank.
3. I type the name with which I saved the bank in the first place.
4. An empty folder with that name is created in the sd card.

**Expected behavior**

**Screenshots**
![2020-09-14-16-50-19.jpg](https://user-images.githubusercontent.com/71260012/93104783-956e5600-f6ae-11ea-9810-b20172f2f445.jpg)![2020-09-14-16-50-32.jpg](https://user-images.githubusercontent.com/71260012/93104794-9901dd00-f6ae-11ea-928b-c5560e38c483.jpg)![2020-09-14-16-50-47.jpg](https://user-images.githubusercontent.com/71260012/93104805-9bfccd80-f6ae-11ea-895c-e3ee9562d5ec.jpg)![2020-09-14-16-51-09.jpg](https://user-images.githubusercontent.com/71260012/93104815-9f905480-f6ae-11ea-9a06-c3184164a4f7.jpg)![2020-09-14-16-51-17.jpg](https://user-images.githubusercontent.com/71260012/93104832-a323db80-f6ae-11ea-9cd8-c581e752d043.jpg)![2020-09-14-16-51-36.jpg](https://user-images.githubusercontent.com/71260012/93104839-a6b76280-f6ae-11ea-8ed5-e805d0deed58.jpg)![2020-09-14-16-52-02.jpg](https://user-images.githubusercontent.com/71260012/93104854-aae38000-f6ae-11ea-8a65-5157cbe6e6ff.jpg)![2020-09-14-16-52-12.jpg](https://user-images.githubusercontent.com/71260012/93104867-adde7080-f6ae-11ea-859f-32eb9c5fcc46.jpg)

**Desktop (please complete the following information):**
 
Windows 10 Home
Version 2004
Operating system version 
19041.450
64 bits

**Additional context**

**Comment by meanmedianmoge** [comment]
This is related to #69 and is due to the strange choice of the Windows directory separator (\\ vs /). Upon importing the patches, they will not be named correctly, so you cannot export them properly. I will address the import process first and see if that fixes the export issue.

**Comment by meanmedianmoge** [comment]
Simple fix, closed along with #69
