### ISSUE TITLE
Solved: App not opening on macOS (solution - see the release notes for terminal commands)

### ISSUE THREAD

**Issue by devilsinkpot** [meanmedianmoge/zoia_lib#76]
Trying to open the app doesn't work for me.

- I downloaded, unzipped, did NO changes to the app folder.
- there is no pref.json present and no `.ZoiaLibraryApp` folder, neither in `~/Library/Application Support/` nor in `/Library/Application Support/`
- When opening by double-click, the app can't open due to an unknown developer (as expected)
- Opening by right-click > open gives the open animation but the app doesn't run
- same affect for `sudo /ZOIALibrarian.app/Contens/MacOS/startup`
- tested on 2x MacPro 6,2, one running Catalina, one Big Sur Beta 8 and a MacBook Pro either booted in one of these

Any help appreciated!

**Comment by bengersfood** [comment]
I can confirm similar here. 
I am running Catalina on iMac (Retina 5K, 27-inch, Late 2014) 4 GHz Quad-Core Intel Core i7
I have Catalina's gatekeeper function disabled so can launch apps from unknown developers directly
As above, the open animation happens but the app doesn't run. Right-click open makes not difference

**Comment by meanmedianmoge** [comment]
@devilsinkpot @bengersfood there should be an error message displayed in the Terminal window when attempting to run from the command line. Do you mind taking a screenshot? That will help debug this.

As for the .app file not working - I'm truly stumped. I'm using Pyinstaller for the bundling process (with all the necessary setup), and it still doesn't wanna see the resource files that are where they need to be). Hence why I included the terminal commands.

**Comment by bengersfood** [comment]
I am a little hazy about launching apps from the Terminal. I think I followed the right procedure and I got this message: LSOpenURLsWithRole() failed for the application /Applications/ZOIALibrarian/ZOIALibrarian.app with error -10810

If open is the wrong command to you please explain the procedure to me and I will happily follow your instructions

**Comment by devilsinkpot** [comment]
![Screenshot 2020-09-26 at 17 14 14](https://user-images.githubusercontent.com/60776417/94343924-f5082200-001b-11eb-8edf-f6e3169c6dab.png)
Thanks for your support, @meanmedianmoge and @bengersfood!

For me, Terminal shows no error, it just freezes until force killed. But this is what console has to offer.

**Comment by bengersfood** [comment]
here's all console message with ZOIA in them when I try and launch with a double click from finder

<img width="1541" alt="Screenshot 2020-09-26 at 16 27 46" src="https://user-images.githubusercontent.com/43231443/94344191-8031e980-0015-11eb-9529-6b0753be5dac.png">

**Comment by meanmedianmoge** [comment]
@bengersfood @devilsinkpot thanks for the context - unfortunately I have no clue how to read the Console logs. It seems like the .app file isn’t going to work for anyone, which is unfortunate, but at least there’s an alternative.

This is the simplest way to open the app - it assumes you keep the unzipped folder in Downloads, but any location will work:
`cd Downloads/ZOIALibrarian-Mac-1.0
./ZOIALibrarian.app/Contents/MacOS/startup
`

If there are issues with those commands (really just the second one), an error message should pop up in Terminal. The only other thing I can think of is if there is an additional folder between the unzipped directory and /ZoiaLibrarian.app - if so, that requires going one extra level down in the cd command. Hopefully that makes sense!

**Comment by bengersfood** [comment]
I do that and get this:

Traceback (most recent call last):
  File "startup.py", line 31, in <module>
  File "ZOIALibrarian_main.py", line 182, in __init__
IndexError: list index out of range
[5747] Failed to execute script startup

**Comment by bengersfood** [comment]
I did get the splash screen for a moment or two - which is certainly an improvement

**Comment by meanmedianmoge** [comment]
That is an improvement! And I have a fix: 

If you've used an earlier version of the application, you'll have to delete the saved preferences file from the local backend. On Mac, delete /Users/user/.Library\Application Support/.ZoiaLibraryApp/pref.json (if it exists).

**Comment by devilsinkpot** [comment]
@meanmedianmoge this is the way I start from Terminal:
`sudo ./ZOIALibrarian.app/Contents/MacOS/startup`

The folder` ~/Library/.ZOIALibraryApp/` is present but has no files in it. Only a subfolder called "banks".

**Comment by bengersfood** [comment]
That worked! I had to re-discover how to show hidden folders. I had looked to delete the prefs file previously but did not realize I was looking for a hidden folder.

So is running a pair of Terminal commands the only way to launch the app?

**Comment by meanmedianmoge** [comment]
@bengersfood glad to hear it! Yeah, sorry about the hidden folders - originally users wouldn’t ever need to find those, but we uncovered that pref bug immediately before deployment (it’ll be a more graceful version switch in 1.1).

And yes, those two are your ticket in. Apologies for any inconvenience! I really tried getting the .app file to work, but it just.. won’t.

@devilsinkpot what folder are you currently in when you run that sudo command?

**Comment by bengersfood** [comment]
Good luck. The first two Mac betas opened OK. The final beta and now this 1.0 build has these problems. Not certain what changed.

**Comment by meanmedianmoge** [comment]
Thanks! It’s cause we added more resource files for the app to utilize (things like the themes, module index to parse the binary, and documentation) - those need to be packaged in a specific manner. And while I’m doing it as instructed, it has yet to work as intended.

**Comment by devilsinkpot** [comment]
Any more troubleshooting you can advise me on?

**Comment by meanmedianmoge** [comment]
I don't think you need the sudo here. Also folder are you currently in when you run that command?

**Comment by devilsinkpot** [comment]
I tried in ~/Downloads/ZOIALibrarian as well as copying everything to ~/Applications.

I also just tried it on a fresh install of Catalina in a VM with Parallels and it doesn't work either.

**Comment by devilsinkpot** [comment]
I find it very strange, that you simply close this issue that I opened when someone else who just chimed on with an obvious different issue gets his solved. 🤨

**Comment by bengersfood** [comment]
Just adding in - in case it is helpful - that if the current directory is not set to the ZOIALibrarian folder (with the app in), then the startup command does not work. I imagine you know this, but I though I should mention it just in case.

**Comment by meanmedianmoge** [comment]
@devilsinkpot I closed this because there doesn’t seem to be any reason (or error) that your issues are separate from @bengersfood 

If those two commands (provided in my comment right below the Console traceback) are still not working, I apologize, but they are consistent for other users. If you reach a specific error message in Terminal, that would be greatly helpful in moving this forward.

Side-note: I never tested the app in a VM, so no clue on what might happen in that environment.

**Comment by meanmedianmoge** [comment]
@devilsinkpot @bengersfood can either of you try the Mac release here https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.0 ? I updated it and it should run successfully when you double-click.

**Comment by bengersfood** [comment]
Launches with a double click from the downloads folder for me! Hurrah

Mac OS Gatekeeper asked it's usual questions (though I have it set to be far less aggressive than Apple would like), but otherwise all good. So does this .app file replace the whole complicated folder and contents that I was previously treating as the ZOIALibraian installation?

**Comment by meanmedianmoge** [comment]
Excellent news! Yes, you can simple delete the old contents data (should be the old app file and ZOIALibrarian folder that you unzipped) and you’ll be all set. No need to touch the files in the backend (/Library), as it’ll see that they are there and continue work as if nothing changed.
