### ISSUE TITLE
Zoia Librarian doesn't not launch MacOS 10.13.6

### ISSUE THREAD

**Issue by p1afff** [meanmedianmoge/zoia_lib#81]
Hello, it's first time install, and the app never launches. When using the Finder ZOIALibrarian.app method, after first classic security message, nothing is displayed. I tried the Terminal command method, still unsuccessful. I have this message :
 
`ImportError: dlopen(/Users/MYUSERNAME/Downloads/ZOIALibrarian-Mac-1.0/ZOIALibrarian.app/Contents/MacOS/select.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/MYUSERNAME/Downloads/ZOIALibrarian-Mac-1.0/ZOIALibrarian.app/Contents/MacOS/select.cpython-38-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/MYUSERNAME/Downloads/ZOIALibrarian-Mac-1.0/ZOIALibrarian.app/Contents/MacOS/select.cpython-38-darwin.so
[18076] Failed to execute script pyi_rth_multiprocessing`

Folder is in the Downloads folder, MacOS 10.13.6

**Comment by meanmedianmoge** [comment]
You might be the first person I've seen using 10.13 - this is great information, thanks for the error traceback! Will investigate and see if we can remedy this for you (and others).

**Comment by meanmedianmoge** [comment]
@p1afff can you try the newly updated Mac release in here https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.0? Should be better now. If the issue still persists, I'll have to dive into that error message a bit.

**Comment by p1afff** [comment]
OK. Mmm, this time the dl link was only the app, right ? So I kept previous folder and replaced only the app. 
Still not working, different message in Terminal :
`-bash: ./ZOIALibrarian.app/Contents/MacOS/startup: No such file or directory
MacBook-Pro-de-Philippe:ZOIALibrarian-Mac-1.0 MYUSERNAME$`

**Comment by meanmedianmoge** [comment]
You can get rid of the folder and just keep the app file! A double-click on that should be all that you need, no terminal necessary.

**Comment by p1afff** [comment]
Still not working. Don't know what to do now ?

**Comment by meanmedianmoge** [comment]
Ok thanks for letting me know. Looks to be due to some incompatibilities with older versions of OS X (which I really can’t test for.. unfortunately). As mentioned before, it’s worked on 10.14 and higher. Are you opposed to upgrading your OS? That would likely get a much faster result than me tracking down a consistent way to test on older version.

**Comment by p1afff** [comment]
Yes I will, just cautious you know with plug-ins, drivers etc ... and a bit bored with the time to do the update job ah ah So many things to update 
Thanks for your efforts

**Comment by meanmedianmoge** [comment]
Apologies for that! I do appreciate you taking the time to try it out and submit a ticket - if I ever am able to support 10.13, I'll ping you again. Closing.
