### ISSUE TITLE
Local Storage View Blank after Download/Import

### ISSUE THREAD

**Issue by rogueblue42** [meanmedianmoge/zoia_lib#82]
**Describe the bug**
In windows 10, the Local Storage View is empty after re-launching the program. In the PatchStorage View, it seems to know what files I already downloaded, which is odd because no local file show up. I would imagine it's supposed to save information on the local files?

In addition, now that I've shut down my computer and re-lauched, I can't even import files. I select a directory to import multiple patches and nothing shows up in the local storage view.

I also hit download on a new patch in patchstorage view and after it shows it is downloaded, it also doesn't show up in local storage view.

**To Reproduce**
Pretty well described above.

**Expected behavior**
The local storage view should show files.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by meanmedianmoge** [comment]
@rogueblue42 did you do “download all”? If so, this is due to #80

**Comment by rogueblue42** [comment]
No, I didn't use a download all command. In fact, I don't even see that command.2

**Comment by rogueblue42** [comment]
It seems to have imported files but they don't show up. This is what happens after I try importing a single bin file from the same directory as I used to import multiple patches. You can see the background is blank where the files used to be listed.

![image](https://user-images.githubusercontent.com/72348099/95018947-757be380-0617-11eb-862d-d53fafcb2735.png)

**Comment by meanmedianmoge** [comment]
“Download all” is a button above the PS table on the first tab - I’d be very concerned if that was missing from the UI completely.

Seems like there’s some issue with the backend files - likely some additional data ended up there that shouldn’t have. On windows, go to `C:\Users\user\AppData\Roaming\.ZoiaLibraryApp`

The structure of that directory should be:
.ZoiaLibraryApp
- 5 or 6 digit directories (patch files and metadata)
- Banks (json bank files)
- data.json (PS patch list and metadata)
- pref.json (UI saved settings)

If there are any other directories or files within, the Local table will not display. For this to be fully resolved, I’d need a screenshot of the offending file(s) so I can diagnose why they ended up there in the first place.

Let me know if you run into issues.

**Comment by rogueblue42** [comment]
I didn't understand your first question. No, I didn't press download all under the patchstorage view. I thought you meant in the local storage view. Sorry!

**Comment by rogueblue42** [comment]
There are a lot more directories than 5 or 6:
![image](https://user-images.githubusercontent.com/72348099/95020870-9d247900-0622-11eb-9e17-fde38637ac4d.png)
![image](https://user-images.githubusercontent.com/72348099/95020881-a4e41d80-0622-11eb-8c3f-aa75ae52fc7b.png)

**Comment by rogueblue42** [comment]
Thanks for letting me know where this directory was. I closed the Librarian, deleted the C:\Users\user\AppData\Roaming\.ZoiaLibraryApp directory, and relaunched Librarian. I then imported my patches using the File>Import Multiple Patches. Now they all show up again. They also are synched with the PatchStorage View because it knows what I've already downloaded.

There are still many directories, nearly 60, similar to my previous image but now doesn't show the temp folder or the temp.zip file.
![image](https://user-images.githubusercontent.com/72348099/95021419-b4b13100-0625-11eb-8251-3aa5b892304a.png)

**Comment by meanmedianmoge** [comment]
Heh, I meant 5 or 6-digit numbered, not that there’s only 5 or 6 of them.

Glad you were able to resolve the issue! Did you take a peek at what’s inside the Temp folder and zip before you deleted them?

**Comment by rogueblue42** [comment]
Ahh, I see what you meant now. Still having my morning coffee...

Yes, I saved a copy of the whole directory. The Temp folder was empty and the Temp.zip is an invalid zip file. I don't know where these came from because there's no matching file in the import directories.

**Comment by meanmedianmoge** [comment]
Not a problem. Hmm, do you recall the particular patch you downloaded or imported before noticing the problem? That would help identify what caused it. As mentioned, ZoiaMurf v2 is a known issue that would cause a similar problem. I haven’t run into problems with imports yet, so this may be the first.

For now, I’ll edit the way it loads the Local table (ignoring files/directories that would otherwise cause error).

**Comment by rogueblue42** [comment]
Unfortunately, I don't recall. I used it last weekend and it worked fine then opened it back up today to find it wasn't working. Sorry not very helpful!

I'll let you know if it happens again. Thanks for your help!
