### ISSUE TITLE
Ability to rate the patches locally/globally

### ISSUE THREAD

**Issue by Arxi** [meanmedianmoge/zoia_lib#84]
**Is your feature request related to a problem? Please describe.**
When testing out many (potentially hundreds) of patches, users quickly lose track of what patches they have already tried on ZOIA and if they liked them.

**Describe the solution you'd like**
I'd love to see some local rating system in place. For example, the ability to mark any patch with zero, one, two or three stars. This would enable me to distinguish between patches I have already tried (those who have something else than zero stars), those that I like and those I don't like. 

The ability to list/filter out only patches with rating and sort them by rating would enhance the experience.

The ability to add custom timestamped note to each patch could also enhance the experience. 

The ability to exchange these ratings with all the other users (i.e. see what patches have the highest rating between all the users) is something that is missing even on Patchstorage itself. I realize, however, that this would require some backend server to manage the information exchange.

**Describe alternatives you've considered**
I'm currently using a Google Sheet for this purpose, but would love to be able to have everything in one place in the Librarian.

What do you think?

**Comment by meanmedianmoge** [comment]
A rating feature was something we discussed initially, so I'm all for adding it. Would be easy enough to build into the patch metadata and display in the Local Storage right-hand panel. I'm hesitant on the global/sharing aspect, really. The likes function already serves as a way to measure popularity (note that I'm not saying whether it's a flawed system, just that it exists), so I'm not sure what benefit would arise from adding additional rating layers *on PatchStorage* (I'm fully on board with the local ratings).

To do:
- Add rating system for local patches (0-3 stars)
- Add sort and filter methods for ratings

Needs clarification:
- Timestamped notes? What exactly do you mean here? Something related to when you make edits to the patch notes?

Won't do:
- Global/shared ratings

**Comment by Arxi** [comment]
Right - I understand what you say about global ratings.

As for notes - I meant the ability to add custom note to the patch, but I didn't realize it's already possible to update the patch notes - see, I never use Local Storage view, mainly PatchStorage View and Banks (and then of course SD Card View when I want to export). So I guess this is useable as it is, thanks!

**Comment by meanmedianmoge** [comment]
Oh yes, the Local table has the "Update Patch Notes" feature which is used after you make additions/removals to the existing notes! I'll get started on the rating system. Thanks for the request!

**Comment by meanmedianmoge** [comment]
This is nearly complete - the remaining step is to add a system to edit the rating on the UI that doesn't also break the tags/cats edit function.
