### ISSUE TITLE
No patch details in Bank View

### ISSUE THREAD

**Issue by barkinggecko** [meanmedianmoge/zoia_lib#86]
**Describe the bug**
Instead of seeing patch details such as Title, Tags and Categories, I only see a list of "Click me to add to bank" buttons in the 'Add to Bank'  section of the Bank tab.

**To Reproduce**
1. Go to 'Banks' tab
2. See error in 'Add to Bank' pane

**Expected behavior**
Per the instructional video (https://www.youtube.com/watch?v=JLOUrWtG1Pk) I would expect the contents of the 'Add to Bank'  section of the Bank tab to include Title, Tags, Categories and 'Add to bank' buttons. I only see the buttons. The buttons work but without the details I can't see which patch the buttons are linked to.

**Screenshots**
![image](https://user-images.githubusercontent.com/74066729/98393287-08cf8b00-2094-11eb-9d52-dc9269da0352.png)

**Desktop (please complete the following information):**
 - OS: ![image](https://user-images.githubusercontent.com/74066729/98393703-a2973800-2094-11eb-9c4a-c22a09929fcc.png)
 - ZOIA Librarian Version 1.0
 
**Additional context**

**Comment by john-breton** [comment]
Hm, this seems like a column size issue for the third table (so the title, tags, and categories are being hidden by the last Add to bank column). I believe @meanmedianmoge added an option to reset the sizing of columns in either File or Options menu items. Can you try out that resizing feature to see if the problem persists?

**Comment by meanmedianmoge** [comment]
Thanks @john-breton. That's right @barkinggecko, there's a Reset UI option that should fix that for you. Version 1.1 is going to have some better default values for the window sizing, as it's pretty easy for users to get into this situation when moving things around.

**Comment by barkinggecko** [comment]
Thankyou both! That did the trick.
