### ISSUE TITLE
Assign to next free slot number 

### ISSUE THREAD

**Issue by personalnadir** [meanmedianmoge/zoia_lib#91]
**Describe the solution you'd like**
When exporting patches to SD card from the Local Storage View, it would be nice to have an option to select the next blank slot number. It would also be handy to see the list of patches when assigning as well.

**Comment by meanmedianmoge** [comment]
This has been implemented. It will increment the default slot number as you export to the "to_zoia" folder. As for the viewing the list of patches, you can easily check that in the SD view under the "to_zoia" directory.
