### ISSUE TITLE
That slot is occupied: show patch name 

### ISSUE THREAD

**Issue by personalnadir** [meanmedianmoge/zoia_lib#92]
**Is your feature request related to a problem? Please describe.**
When exporting from Local Storage View if a slot is already occupied the popup does not display any details about the patch that might be overwritten.

**Describe the solution you'd like**
The name, and perhaps a description of the patch already occupying the slot.

**Comment by meanmedianmoge** [comment]
This has been implemented, however it only can use the name of the file from the SD card, so there's no way to (easily) relay that back to a particular patch for displaying it's metadata. Hopefully the solution presented in v1.1 will suffice.
