### ISSUE TITLE
Drag-and-drop doesn't work properly (sometimes) if SD path is selected/in use

### ISSUE THREAD

**Issue by meanmedianmoge** [meanmedianmoge/zoia_lib#93]
**Describe the bug**
When SD card path is selected/in use, drag-and-drop doesn't function properly in the SD or Bank tabs.

**To Reproduce**
1. Go to SD tab, choose a location for the SD card
2. Attempt to move the patches in an SD directory in the bottom two tables
3. Do the same with moving patches in the Bank tab (from the local table to the bank/within the bank)

**Expected behavior**
Expected drag-and-drop to work, regardless of SD status.

**Screenshots**

**Desktop (please complete the following information):**
- macOS 10.15.4
- Affects both master and v1.1 branches

**Comment by meanmedianmoge** [comment]
This bug is odd, because now it's working perfectly fine. Not seeing any particular reason for it either, but will keep open for now and keep digging.

**Comment by Tnunnery** [comment]
Same issue here. I have no ability to drag and drop in the SD card view.

**Comment by meanmedianmoge** [comment]
This seems temperamental at best, as I haven't encountered the issue in a couple weeks. When it did occur, I had some success by resetting the SD location.

**Comment by meanmedianmoge** [comment]
Going to close this for now - newer app bundle in the release seems very stable. Feel free to re-open if necessary.
