### ISSUE TITLE
No Patch Names or Details

### ISSUE THREAD

**Issue by satshabad-cr** [meanmedianmoge/zoia_lib#96]
**Describe the bug**
There's no info about any patches

**To Reproduce**
1. download the app and run it on ubuntu 20.04

**Expected behavior**
Expect to see some patch names, from the screenshots in the manual this is what I expect

**Screenshots**
![image](https://user-images.githubusercontent.com/45502068/119278379-bbeb7600-bbd9-11eb-9167-d84c5a520ac8.png)

**Desktop:**
Ubuntu 20.04

**Comment by meanmedianmoge** [comment]
Try resetting the UI from the options menu - the table columns sometimes get messed up. This will be mitigated in version 1.1 as well with the improved default UI settings.
