### ISSUE TITLE
Version 1.1 hangs on macOS 11.4

### ISSUE THREAD

**Issue by PeteKraft** [meanmedianmoge/zoia_lib#98]
I just downloaded the latest version 1.1 of ZOIA Librarian, never had a previous version installed.

Upon launch (after jumping through the macOS security hoops..) I see some internet action to patch storage, then the menu bar comes up (no splash screen) and then the application hangs.

I then tried the previous version (1.0 with the BigSur hot fix) and it launched perfectly to the GUI.

Is there any info that I can provide that might be helpful ?

**Comment by meanmedianmoge** [comment]
Thanks for the report, Pete. The version of BigSur I have is 11.2.3 (and it does work with the zip included in the release) so I will need to update to test.

**Comment by sadrian80** [comment]
For me it doesn't open on Big Sur 11.3, 11.4, also tested on a VM running a fresh and pure vanilla instance of 11.3.

Download, unzip, move to Applications, right-click open, open anyway on security notice. From there on "Application not responding", process running at 99–100% CPU, increasing memory use by ~10M per second.

![image](https://user-images.githubusercontent.com/77888082/121782599-959e7200-cbaa-11eb-9493-e117851b63a1.png)

If I can collect any info that might help you troubleshoot, let me know.

**Comment by meanmedianmoge** [comment]
@PeteKraft @sadrian80 could either of you try the updated Mac release here: https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.1? I added a bugfix which hopefully addresses this BigSur business.

**Comment by PeteKraft** [comment]
I just tested the new version, but sadly it doesn't solve the problem... It still freezes after a few seconds...

**Comment by meanmedianmoge** [comment]
I just replaced the zip file in the Mac release for that link so it should be up-to-date. BigSur is dumb; I'll keep trying to fix this. Apologies for the hassle.

**Comment by meanmedianmoge** [comment]
@PeteKraft Can you do me a favor and try the following commands from a Mac terminal? The first command is just to navigate where you put the .app file (I'm assuming `Downloads` but it could be anywhere). The second will attempt to open the app and will print an error in the Terminal window, which I can use for debugging.

```
cd Downloads
./ZOIALibrarian.app/Contents/MacOS/ZOIA Librarian
```

**Comment by PeteKraft** [comment]
Yes indeed, I tried a fresh download and reinstall, and then launched from terminal (had to escape the spaces though) and after a few moments it freezes, without any message in terminal.

I do notice that upon launch, the app makes a request to patchstorage, but from what I can see there seems to be very minimal traffic... it doesn't look like all patches are downloaded... might this indicate a possible cause ?
Is there a way I can verify if anything is downloaded ?

**Comment by meanmedianmoge** [comment]
You can check the local backend to see if any files are generated, which is here: `/Users/user/Library/Application Support/.ZoiaLibraryApp`. It should look something like the screenshot I attached below, with the primary two items being the "Banks" directory and the `data.json` file. (Those extra directories are the patches I have downloaded/imported). The important bit is the json, which contains all the extracted PatchStorage metadata we get from their API. If something is going wrong that call, the json will be empty, or missing a lot of its metadata.

<img width="678" alt="Screen Shot 2021-07-02 at 10 56 57 AM" src="https://user-images.githubusercontent.com/51132973/124293036-3a65fc80-db24-11eb-821e-54a77e90fb51.png">

**Comment by PeteKraft** [comment]
I just verified, and I do have the Banks folder (which is empty) and a data.json file that seems correct. It's 963 kb and it looks like propper json data inside.
Upon launching Zoia Librarian, I also see that the data.json is updated, so it seems that a succesfull call is being made to patchstorage.

**Comment by meanmedianmoge** [comment]
@PeteKraft Can you please try the updated zip in the release? I just confirmed it to open on BigSur 11.2 after making a change.

**Comment by PeteKraft** [comment]
Yes ! That fixed it... thanks so much !
